/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const City = IDL.Text;
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'city' : City,
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const Transporter = IDL.Record({
  'id' : IDL.Nat,
  'city' : City,
  'name' : IDL.Text,
  'contactNumber' : IDL.Text,
});
export const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'staff' : IDL.Null });
export const AppUser = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
  'principalId' : IDL.Text,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderPriority = IDL.Variant({
  'normal' : IDL.Null,
  'urgent' : IDL.Null,
  'veryUrgent' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'dispatched' : IDL.Null,
  'delivered' : IDL.Null,
  'unknown' : IDL.Null,
  'packed' : IDL.Null,
  'pendingDispatch' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'dispatchPdfId' : IDL.Text,
  'billPhotoId' : IDL.Text,
  'customerPhone' : IDL.Text,
  'salesperson' : IDL.Text,
  'lrPhotoId' : IDL.Text,
  'createdBy' : IDL.Text,
  'dispatchDate' : IDL.Text,
  'orderDate' : IDL.Int,
  'orderValue' : IDL.Float64,
  'transportReceiptId' : IDL.Text,
  'lrNumber' : IDL.Text,
  'lastUpdatedBy' : IDL.Text,
  'packingListId' : IDL.Text,
  'otherDocId' : IDL.Text,
  'notes' : IDL.Text,
  'customerId' : IDL.Nat,
  'priority' : OrderPriority,
  'lastUpdatedTime' : IDL.Int,
  'transporterId' : IDL.Nat,
  'invoiceDocId' : IDL.Text,
  'orderNumber' : IDL.Text,
  'deliveredDate' : IDL.Text,
  'transporterName' : IDL.Text,
  'customerCity' : City,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
});
export const CompanySettings = IDL.Record({
  'companyLogoId' : IDL.Text,
  'companyEmail' : IDL.Text,
  'companyName' : IDL.Text,
  'companyPhone' : IDL.Text,
  'companyAddress' : IDL.Text,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'salesperson' : IDL.Text,
  'createdAt' : IDL.Int,
  'dispatchDate' : IDL.Text,
  'isRead' : IDL.Bool,
  'orderId' : IDL.Nat,
  'lrNumber' : IDL.Text,
  'orderNumber' : IDL.Text,
  'transporterName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCustomer' : IDL.Func([IDL.Text, IDL.Text, City], [Customer], []),
  'addTransporter' : IDL.Func([IDL.Text, IDL.Text, City], [Transporter], []),
  'addUser' : IDL.Func([IDL.Text, IDL.Text, UserRole, IDL.Text], [AppUser], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'bootstrapAdmin' : IDL.Func([IDL.Text, IDL.Text], [AppUser], []),
  'createOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        OrderPriority,
      ],
      [IDL.Opt(Order)],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getCompanySettings' : IDL.Func([], [IDL.Opt(CompanySettings)], ['query']),
  'getCustomer' : IDL.Func([IDL.Nat], [IDL.Opt(Customer)], ['query']),
  'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getDailyDispatchReport' : IDL.Func(
      [],
      [
        IDL.Record({
          'todayDispatched' : IDL.Nat,
          'todayCreated' : IDL.Nat,
          'delivered' : IDL.Nat,
          'dispatchedToday' : IDL.Vec(Order),
          'pendingDispatch' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getNotificationsForSalesperson' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getOrderStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'total' : IDL.Nat,
          'dispatched' : IDL.Nat,
          'delivered' : IDL.Nat,
          'packed' : IDL.Nat,
          'pendingDispatch' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrdersByPhone' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getPendingDispatchOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getTransporter' : IDL.Func([IDL.Nat], [IDL.Opt(Transporter)], ['query']),
  'getTransporters' : IDL.Func([], [IDL.Vec(Transporter)], ['query']),
  'getUnreadNotificationCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getUserByEmail' : IDL.Func([IDL.Text], [IDL.Opt(AppUser)], ['query']),
  'getUserByPrincipal' : IDL.Func([IDL.Text], [IDL.Opt(AppUser)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUsers' : IDL.Func([], [IDL.Vec(AppUser)], ['query']),
  'hasUsers' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
  'removeUser' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCompanySettings' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [CompanySettings],
      [],
    ),
  'updateOrderDispatch' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        OrderStatus,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Opt(Order)],
      [],
    ),
  'updateOrderInfo' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Float64,
        IDL.Text,
        OrderPriority,
        IDL.Text,
      ],
      [IDL.Opt(Order)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const City = IDL.Text;
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'city' : City,
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Transporter = IDL.Record({
    'id' : IDL.Nat,
    'city' : City,
    'name' : IDL.Text,
    'contactNumber' : IDL.Text,
  });
  const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'staff' : IDL.Null });
  const AppUser = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
    'principalId' : IDL.Text,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderPriority = IDL.Variant({
    'normal' : IDL.Null,
    'urgent' : IDL.Null,
    'veryUrgent' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'dispatched' : IDL.Null,
    'delivered' : IDL.Null,
    'unknown' : IDL.Null,
    'packed' : IDL.Null,
    'pendingDispatch' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'dispatchPdfId' : IDL.Text,
    'billPhotoId' : IDL.Text,
    'customerPhone' : IDL.Text,
    'salesperson' : IDL.Text,
    'lrPhotoId' : IDL.Text,
    'createdBy' : IDL.Text,
    'dispatchDate' : IDL.Text,
    'orderDate' : IDL.Int,
    'orderValue' : IDL.Float64,
    'transportReceiptId' : IDL.Text,
    'lrNumber' : IDL.Text,
    'lastUpdatedBy' : IDL.Text,
    'packingListId' : IDL.Text,
    'otherDocId' : IDL.Text,
    'notes' : IDL.Text,
    'customerId' : IDL.Nat,
    'priority' : OrderPriority,
    'lastUpdatedTime' : IDL.Int,
    'transporterId' : IDL.Nat,
    'invoiceDocId' : IDL.Text,
    'orderNumber' : IDL.Text,
    'deliveredDate' : IDL.Text,
    'transporterName' : IDL.Text,
    'customerCity' : City,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  const CompanySettings = IDL.Record({
    'companyLogoId' : IDL.Text,
    'companyEmail' : IDL.Text,
    'companyName' : IDL.Text,
    'companyPhone' : IDL.Text,
    'companyAddress' : IDL.Text,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'salesperson' : IDL.Text,
    'createdAt' : IDL.Int,
    'dispatchDate' : IDL.Text,
    'isRead' : IDL.Bool,
    'orderId' : IDL.Nat,
    'lrNumber' : IDL.Text,
    'orderNumber' : IDL.Text,
    'transporterName' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCustomer' : IDL.Func([IDL.Text, IDL.Text, City], [Customer], []),
    'addTransporter' : IDL.Func([IDL.Text, IDL.Text, City], [Transporter], []),
    'addUser' : IDL.Func(
        [IDL.Text, IDL.Text, UserRole, IDL.Text],
        [AppUser],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'bootstrapAdmin' : IDL.Func([IDL.Text, IDL.Text], [AppUser], []),
    'createOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          OrderPriority,
        ],
        [IDL.Opt(Order)],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getCompanySettings' : IDL.Func([], [IDL.Opt(CompanySettings)], ['query']),
    'getCustomer' : IDL.Func([IDL.Nat], [IDL.Opt(Customer)], ['query']),
    'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getDailyDispatchReport' : IDL.Func(
        [],
        [
          IDL.Record({
            'todayDispatched' : IDL.Nat,
            'todayCreated' : IDL.Nat,
            'delivered' : IDL.Nat,
            'dispatchedToday' : IDL.Vec(Order),
            'pendingDispatch' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getNotificationsForSalesperson' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getOrderStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'total' : IDL.Nat,
            'dispatched' : IDL.Nat,
            'delivered' : IDL.Nat,
            'packed' : IDL.Nat,
            'pendingDispatch' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrdersByPhone' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getPendingDispatchOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getTransporter' : IDL.Func([IDL.Nat], [IDL.Opt(Transporter)], ['query']),
    'getTransporters' : IDL.Func([], [IDL.Vec(Transporter)], ['query']),
    'getUnreadNotificationCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getUserByEmail' : IDL.Func([IDL.Text], [IDL.Opt(AppUser)], ['query']),
    'getUserByPrincipal' : IDL.Func([IDL.Text], [IDL.Opt(AppUser)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUsers' : IDL.Func([], [IDL.Vec(AppUser)], ['query']),
    'hasUsers' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
    'removeUser' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCompanySettings' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [CompanySettings],
        [],
      ),
    'updateOrderDispatch' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          OrderStatus,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Opt(Order)],
        [],
      ),
    'updateOrderInfo' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Float64,
          IDL.Text,
          OrderPriority,
          IDL.Text,
        ],
        [IDL.Opt(Order)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };