/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppUser {
  'id' : bigint,
  'name' : string,
  'role' : UserRole,
  'email' : string,
  'principalId' : string,
}
export type City = string;
export interface Customer {
  'id' : bigint,
  'city' : City,
  'name' : string,
  'phone' : string,
}
export interface Notification {
  'id' : bigint,
  'customerName' : string,
  'salesperson' : string,
  'createdAt' : bigint,
  'dispatchDate' : string,
  'isRead' : boolean,
  'orderId' : bigint,
  'lrNumber' : string,
  'orderNumber' : string,
  'transporterName' : string,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : OrderStatus,
  'billPhotoId' : string,
  'customerPhone' : string,
  'salesperson' : string,
  'lrPhotoId' : string,
  'createdBy' : string,
  'dispatchDate' : string,
  'orderDate' : bigint,
  'orderValue' : number,
  'transportReceiptId' : string,
  'lrNumber' : string,
  'lastUpdatedBy' : string,
  'packingListId' : string,
  'otherDocId' : string,
  'notes' : string,
  'customerId' : bigint,
  'priority' : OrderPriority,
  'lastUpdatedTime' : bigint,
  'transporterId' : bigint,
  'invoiceDocId' : string,
  'orderNumber' : string,
  'deliveredDate' : string,
  'transporterName' : string,
  'customerCity' : City,
}
export type OrderPriority = { 'normal' : null } |
  { 'urgent' : null } |
  { 'veryUrgent' : null };
export type OrderStatus = { 'dispatched' : null } |
  { 'delivered' : null } |
  { 'unknown' : null } |
  { 'packed' : null } |
  { 'pendingDispatch' : null };
export interface Transporter {
  'id' : bigint,
  'city' : City,
  'name' : string,
  'contactNumber' : string,
}
export interface UserProfile {
  'name' : string,
  'role' : UserRole,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'staff' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomer' : ActorMethod<[string, string, City], Customer>,
  'addTransporter' : ActorMethod<[string, string, City], Transporter>,
  'addUser' : ActorMethod<[string, string, UserRole, string], AppUser>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createOrder' : ActorMethod<
    [string, bigint, bigint, number, string, string, OrderPriority],
    [] | [Order]
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getCustomer' : ActorMethod<[bigint], [] | [Customer]>,
  'getCustomers' : ActorMethod<[], Array<Customer>>,
  'getDailyDispatchReport' : ActorMethod<
    [],
    {
      'todayDispatched' : bigint,
      'todayCreated' : bigint,
      'delivered' : bigint,
      'dispatchedToday' : Array<Order>,
      'pendingDispatch' : bigint,
    }
  >,
  'getNotificationsForSalesperson' : ActorMethod<[string], Array<Notification>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getOrderStats' : ActorMethod<
    [],
    {
      'total' : bigint,
      'dispatched' : bigint,
      'delivered' : bigint,
      'packed' : bigint,
      'pendingDispatch' : bigint,
    }
  >,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getOrdersByPhone' : ActorMethod<[string], Array<Order>>,
  'getPendingDispatchOrders' : ActorMethod<[], Array<Order>>,
  'getTransporter' : ActorMethod<[bigint], [] | [Transporter]>,
  'getTransporters' : ActorMethod<[], Array<Transporter>>,
  'getUnreadNotificationCount' : ActorMethod<[string], bigint>,
  'getUserByEmail' : ActorMethod<[string], [] | [AppUser]>,
  'getUserByPrincipal' : ActorMethod<[string], [] | [AppUser]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUsers' : ActorMethod<[], Array<AppUser>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markNotificationRead' : ActorMethod<[bigint], undefined>,
  'removeUser' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateOrderDispatch' : ActorMethod<
    [
      bigint,
      string,
      string,
      OrderStatus,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    [] | [Order]
  >,
  'updateOrderInfo' : ActorMethod<
    [bigint, string, bigint, bigint, number, string, OrderPriority, string],
    [] | [Order]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];