/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Customer {
    id: bigint;
    city: City;
    name: string;
    phone: string;
}
export type City = string;
export interface AppUser {
    id: bigint;
    name: string;
    role: UserRole;
    email: string;
    principalId: string;
}
export interface Order {
    id: bigint;
    customerName: string;
    status: OrderStatus;
    billPhotoId: string;
    customerPhone: string;
    salesperson: string;
    lrPhotoId: string;
    createdBy: string;
    dispatchDate: string;
    orderDate: bigint;
    orderValue: number;
    transportReceiptId: string;
    lrNumber: string;
    lastUpdatedBy: string;
    packingListId: string;
    otherDocId: string;
    notes: string;
    customerId: bigint;
    priority: OrderPriority;
    lastUpdatedTime: bigint;
    transporterId: bigint;
    invoiceDocId: string;
    orderNumber: string;
    deliveredDate: string;
    transporterName: string;
    customerCity: City;
}
export interface Transporter {
    id: bigint;
    city: City;
    name: string;
    contactNumber: string;
}
export interface Notification {
    id: bigint;
    customerName: string;
    salesperson: string;
    createdAt: bigint;
    dispatchDate: string;
    isRead: boolean;
    orderId: bigint;
    lrNumber: string;
    orderNumber: string;
    transporterName: string;
}
export interface UserProfile {
    name: string;
    role: UserRole;
    email: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum OrderPriority {
    normal = "normal",
    urgent = "urgent",
    veryUrgent = "veryUrgent"
}
export enum OrderStatus {
    dispatched = "dispatched",
    delivered = "delivered",
    unknown_ = "unknown",
    packed = "packed",
    pendingDispatch = "pendingDispatch"
}
export enum UserRole {
    admin = "admin",
    staff = "staff"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCustomer(name: string, phone: string, city: City): Promise<Customer>;
    addTransporter(name: string, contactNumber: string, city: City): Promise<Transporter>;
    addUser(name: string, email: string, role: UserRole, principalId: string): Promise<AppUser>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    bootstrapAdmin(name: string, email: string): Promise<AppUser>;
    createOrder(salesperson: string, customerId: bigint, transporterId: bigint, orderValue: number, notes: string, createdBy: string, priority: OrderPriority): Promise<Order | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getCustomer(id: bigint): Promise<Customer | null>;
    getCustomers(): Promise<Array<Customer>>;
    getDailyDispatchReport(): Promise<{
        todayDispatched: bigint;
        todayCreated: bigint;
        delivered: bigint;
        dispatchedToday: Array<Order>;
        pendingDispatch: bigint;
    }>;
    getNotificationsForSalesperson(salesperson: string): Promise<Array<Notification>>;
    getOrder(id: bigint): Promise<Order | null>;
    getOrderStats(): Promise<{
        total: bigint;
        dispatched: bigint;
        delivered: bigint;
        packed: bigint;
        pendingDispatch: bigint;
    }>;
    getOrders(): Promise<Array<Order>>;
    getOrdersByPhone(phone: string): Promise<Array<Order>>;
    getPendingDispatchOrders(): Promise<Array<Order>>;
    getTransporter(id: bigint): Promise<Transporter | null>;
    getTransporters(): Promise<Array<Transporter>>;
    getUnreadNotificationCount(salesperson: string): Promise<bigint>;
    getUserByEmail(email: string): Promise<AppUser | null>;
    getUserByPrincipal(principalText: string): Promise<AppUser | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUsers(): Promise<Array<AppUser>>;
    hasUsers(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    markNotificationRead(id: bigint): Promise<void>;
    removeUser(id: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateOrderDispatch(id: bigint, lrNumber: string, dispatchDate: string, status: OrderStatus, billPhotoId: string, lrPhotoId: string, lastUpdatedBy: string, deliveredDate: string, invoiceDocId: string, packingListId: string, transportReceiptId: string, otherDocId: string): Promise<Order | null>;
    updateOrderInfo(id: bigint, salesperson: string, customerId: bigint, transporterId: bigint, orderValue: number, notes: string, priority: OrderPriority, lastUpdatedBy: string): Promise<Order | null>;
}
import type { AppUser as _AppUser, City as _City, Customer as _Customer, Order as _Order, OrderPriority as _OrderPriority, OrderStatus as _OrderStatus, Transporter as _Transporter, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCustomer(arg0: string, arg1: string, arg2: City): Promise<Customer> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomer(arg0, arg1, arg2);
            return result;
        }
    }
    async addTransporter(arg0: string, arg1: string, arg2: City): Promise<Transporter> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransporter(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransporter(arg0, arg1, arg2);
            return result;
        }
    }
    async addUser(arg0: string, arg1: string, arg2: UserRole, arg3: string): Promise<AppUser> {
        if (this.processError) {
            try {
                const result = await this.actor.addUser(arg0, arg1, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_AppUser_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUser(arg0, arg1, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_AppUser_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bootstrapAdmin(arg0: string, arg1: string): Promise<AppUser> {
        if (this.processError) {
            try {
                const result = await this.actor.bootstrapAdmin(arg0, arg1);
                return from_candid_AppUser_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bootstrapAdmin(arg0, arg1);
            return from_candid_AppUser_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async createOrder(arg0: string, arg1: bigint, arg2: bigint, arg3: number, arg4: string, arg5: string, arg6: OrderPriority): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_OrderPriority_n16(this._uploadFile, this._downloadFile, arg6));
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_OrderPriority_n16(this._uploadFile, this._downloadFile, arg6));
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomer(arg0: bigint): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomers();
            return result;
        }
    }
    async getDailyDispatchReport(): Promise<{
        todayDispatched: bigint;
        todayCreated: bigint;
        delivered: bigint;
        dispatchedToday: Array<Order>;
        pendingDispatch: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyDispatchReport();
                return from_candid_record_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyDispatchReport();
            return from_candid_record_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotificationsForSalesperson(arg0: string): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotificationsForSalesperson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotificationsForSalesperson(arg0);
            return result;
        }
    }
    async getOrder(arg0: bigint): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderStats(): Promise<{
        total: bigint;
        dispatched: bigint;
        delivered: bigint;
        packed: bigint;
        pendingDispatch: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderStats();
            return result;
        }
    }
    async getOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrders();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrders();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersByPhone(arg0: string): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByPhone(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByPhone(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingDispatchOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingDispatchOrders();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingDispatchOrders();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransporter(arg0: bigint): Promise<Transporter | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransporter(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransporter(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransporters(): Promise<Array<Transporter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransporters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransporters();
            return result;
        }
    }
    async getUnreadNotificationCount(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadNotificationCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadNotificationCount(arg0);
            return result;
        }
    }
    async getUserByEmail(arg0: string): Promise<AppUser | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserByEmail(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserByEmail(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserByPrincipal(arg0: string): Promise<AppUser | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserByPrincipal(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserByPrincipal(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsers(): Promise<Array<AppUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsers();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsers();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasUsers(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasUsers();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markNotificationRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async removeUser(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeUser(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateOrderDispatch(arg0: bigint, arg1: string, arg2: string, arg3: OrderStatus, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string, arg9: string, arg10: string, arg11: string): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderDispatch(arg0, arg1, arg2, to_candid_OrderStatus_n38(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderDispatch(arg0, arg1, arg2, to_candid_OrderStatus_n38(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOrderInfo(arg0: bigint, arg1: string, arg2: bigint, arg3: bigint, arg4: number, arg5: string, arg6: OrderPriority, arg7: string): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderInfo(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_OrderPriority_n16(this._uploadFile, this._downloadFile, arg6), arg7);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderInfo(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_OrderPriority_n16(this._uploadFile, this._downloadFile, arg6), arg7);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AppUser_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppUser): AppUser {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_OrderPriority_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderPriority): OrderPriority {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Customer]): Customer | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Transporter]): Transporter | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AppUser]): AppUser | null {
    return value.length === 0 ? null : from_candid_AppUser_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    role: _UserRole;
    email: string;
    principalId: string;
}): {
    id: bigint;
    name: string;
    role: UserRole;
    email: string;
    principalId: string;
} {
    return {
        id: value.id,
        name: value.name,
        role: from_candid_UserRole_n12(_uploadFile, _downloadFile, value.role),
        email: value.email,
        principalId: value.principalId
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    status: _OrderStatus;
    billPhotoId: string;
    customerPhone: string;
    salesperson: string;
    lrPhotoId: string;
    createdBy: string;
    dispatchDate: string;
    orderDate: bigint;
    orderValue: number;
    transportReceiptId: string;
    lrNumber: string;
    lastUpdatedBy: string;
    packingListId: string;
    otherDocId: string;
    notes: string;
    customerId: bigint;
    priority: _OrderPriority;
    lastUpdatedTime: bigint;
    transporterId: bigint;
    invoiceDocId: string;
    orderNumber: string;
    deliveredDate: string;
    transporterName: string;
    customerCity: _City;
}): {
    id: bigint;
    customerName: string;
    status: OrderStatus;
    billPhotoId: string;
    customerPhone: string;
    salesperson: string;
    lrPhotoId: string;
    createdBy: string;
    dispatchDate: string;
    orderDate: bigint;
    orderValue: number;
    transportReceiptId: string;
    lrNumber: string;
    lastUpdatedBy: string;
    packingListId: string;
    otherDocId: string;
    notes: string;
    customerId: bigint;
    priority: OrderPriority;
    lastUpdatedTime: bigint;
    transporterId: bigint;
    invoiceDocId: string;
    orderNumber: string;
    deliveredDate: string;
    transporterName: string;
    customerCity: City;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_OrderStatus_n21(_uploadFile, _downloadFile, value.status),
        billPhotoId: value.billPhotoId,
        customerPhone: value.customerPhone,
        salesperson: value.salesperson,
        lrPhotoId: value.lrPhotoId,
        createdBy: value.createdBy,
        dispatchDate: value.dispatchDate,
        orderDate: value.orderDate,
        orderValue: value.orderValue,
        transportReceiptId: value.transportReceiptId,
        lrNumber: value.lrNumber,
        lastUpdatedBy: value.lastUpdatedBy,
        packingListId: value.packingListId,
        otherDocId: value.otherDocId,
        notes: value.notes,
        customerId: value.customerId,
        priority: from_candid_OrderPriority_n23(_uploadFile, _downloadFile, value.priority),
        lastUpdatedTime: value.lastUpdatedTime,
        transporterId: value.transporterId,
        invoiceDocId: value.invoiceDocId,
        orderNumber: value.orderNumber,
        deliveredDate: value.deliveredDate,
        transporterName: value.transporterName,
        customerCity: value.customerCity
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _UserRole;
    email: string;
}): {
    name: string;
    role: UserRole;
    email: string;
} {
    return {
        name: value.name,
        role: from_candid_UserRole_n12(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    todayDispatched: bigint;
    todayCreated: bigint;
    delivered: bigint;
    dispatchedToday: Array<_Order>;
    pendingDispatch: bigint;
}): {
    todayDispatched: bigint;
    todayCreated: bigint;
    delivered: bigint;
    dispatchedToday: Array<Order>;
    pendingDispatch: bigint;
} {
    return {
        todayDispatched: value.todayDispatched,
        todayCreated: value.todayCreated,
        delivered: value.delivered,
        dispatchedToday: from_candid_vec_n32(_uploadFile, _downloadFile, value.dispatchedToday),
        pendingDispatch: value.pendingDispatch
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    staff: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "staff" in value ? UserRole.staff : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dispatched: null;
} | {
    delivered: null;
} | {
    unknown: null;
} | {
    packed: null;
} | {
    pendingDispatch: null;
}): OrderStatus {
    return "dispatched" in value ? OrderStatus.dispatched : "delivered" in value ? OrderStatus.delivered : "unknown" in value ? OrderStatus.unknown : "packed" in value ? OrderStatus.packed : "pendingDispatch" in value ? OrderStatus.pendingDispatch : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    normal: null;
} | {
    urgent: null;
} | {
    veryUrgent: null;
}): OrderPriority {
    return "normal" in value ? OrderPriority.normal : "urgent" in value ? OrderPriority.urgent : "veryUrgent" in value ? OrderPriority.veryUrgent : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AppUser>): Array<AppUser> {
    return value.map((x)=>from_candid_AppUser_n10(_uploadFile, _downloadFile, x));
}
function to_candid_OrderPriority_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderPriority): _OrderPriority {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: UserRole;
    email: string;
}): {
    name: string;
    role: _UserRole;
    email: string;
} {
    return {
        name: value.name,
        role: to_candid_UserRole_n8(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderPriority): {
    normal: null;
} | {
    urgent: null;
} | {
    veryUrgent: null;
} {
    return value == OrderPriority.normal ? {
        normal: null
    } : value == OrderPriority.urgent ? {
        urgent: null
    } : value == OrderPriority.veryUrgent ? {
        veryUrgent: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    dispatched: null;
} | {
    delivered: null;
} | {
    unknown: null;
} | {
    packed: null;
} | {
    pendingDispatch: null;
} {
    return value == OrderStatus.dispatched ? {
        dispatched: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.unknown ? {
        unknown_: null
    } : value == OrderStatus.packed ? {
        packed: null
    } : value == OrderStatus.pendingDispatch ? {
        pendingDispatch: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    staff: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.staff ? {
        staff: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
